env = Environment()

env.Append(CCFLAGS=['-g'])
env.Append(CPPPATH=['../../nt'])
env.Append(CPPPATH=['../../data'])
env.Append(LIBPATH=['../../nt/bin'])
env.Append(LIBPATH=['../../data/bin'])
env.Append(LIBS=['zmq', 'nt', 'data', 'boost_date_time'])



env.Program(target="testZmqServer.out", source=['testZmqServer.cpp'])
env.Program(target="testZmqClient.out", source=['testZmqClient.cpp'])
env.Program(target="testZmqSubscriber.out", source=['testZmqSubscriber.cpp'])
env.Program(target="testMarket.out", source=['testMarket.cpp'])


